version: '3.3'
services:
  shortener:
    restart: always
    build:
      context: ./shortener
      dockerfile: Dockerfile
    expose:
      - 8000
    depends_on:
      - db
      - cache
    env_file:
      - ./envs/shortener.env
    volumes:
      - ./volumes/logs:/app/logs
      - ./volumes/staticfiles:/app/static

  db:
    restart: always
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - ./envs/db.env
    volumes:
      - ./volumes/db:/var/lib/mysql

  cache:
    restart: always
    image: redis
    ports:
      - 6379:6379

  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./volumes/staticfiles:/app/static
    depends_on:
      - shortener